name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Configurar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.7'

      - name: Compilar APK debug
        run: gradle --no-daemon assembleDebug

      - name: Enviar APK para download
        uses: actions/upload-artifact@v4
        with:
          name: PianoAutoPlayer-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
